apiVersion: v1
kind: Pod
metadata:
  name: cpu-manager-test
  namespace: default
spec:
  restartPolicy: Never
  nodeSelector:
    cpu.example.com/node-class: mixed-cpu-amx-gpu
  containers:
    - name: test
      image: registry.access.redhat.com/ubi9/ubi
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "304"
          memory: "1Gi"
        limits:
          cpu: "304"
          memory: "1Gi"
